# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
        exclude: "^chart/templates/.*\\.ya?ml$"
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs-container
        args:
          - --chart-search-root=.
          - --sort-values-order=file

  - repo: local
    hooks:
      - id: helm-chart-testing
        name: Helm Chart Testing
        language: docker_image
        alias: ct
        files: "^chart/"
        pass_filenames: false
        require_serial: false
        entry: quay.io/helmpack/chart-testing ct lint --chart-dirs .
