{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- with include "base.annotations" (dict "annotations" .Values.ingress.annotations "context" $) }}
  annotations: {{- . | nindent 4 }}
  {{- end }}
  labels: {{- include "base.labels" (dict "labels" .Values.ingress.labels "context" .) | nindent 4 }}
  name: {{ include "base.fullname" . }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts: {{- toYaml .Values.ingress.hostnames | nindent 8 }}
      secretName: {{ default (printf "%s-tls" (first .Values.ingress.hostnames)) .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hostnames }}
    - host: {{ . | quote }}
      http:
        paths:
          {{- range $.Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ default "Prefix" .pathType }}
            backend:
              service:
                name: {{ include "base.fullname" $ }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
