apiVersion: v2
name: base
description: Base Helm chart for Kubernetes - fully values-driven.
type: application
version: 0.2.1
maintainers:
  - name: bonddim
sources:
  - https://github.com/bonddim/helm-base-chart
keywords:
  - application
  - base
  - common
  - deployment
  - service
  - ingress
  - httproute
