{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  {{- with include "base.annotations" (dict "annotations" .Values.httpRoute.annotations "context" $) }}
  annotations: {{- . | nindent 4 }}
  {{- end }}
  labels: {{- include "base.labels" (dict "labels" .Values.httpRoute.labels "context" .) | nindent 4 }}
  name: {{ include "base.fullname" . }}
spec:
  parentRefs: {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  {{- with .Values.httpRoute.hostnames }}
  hostnames: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- $isCanary := and (eq .Values.workload "rollout") (hasKey .Values.strategy "canary") }}
  rules:
    {{- range .Values.httpRoute.rules }}
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ include "base.fullname" $ }}
          port: {{ $.Values.service.port }}
          weight: {{ $isCanary | ternary 100 1 }}
        {{- if $isCanary }}
        - group: ""
          kind: Service
          name: {{ include "base.rolloutServiceName" $ }}
          port: {{ $.Values.service.port }}
          weight: 0
        {{- end }}
      {{- with .filters }}
      filters: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .matches }}
      matches: {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}
