{{- if eq .Values.workload "daemonset" -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  {{- with include "base.annotations" (dict "annotations" .Values.annotations "context" .) }}
  annotations: {{- . | nindent 4 }}
  {{- end }}
  labels: {{- include "base.labels" (dict "labels" .Values.labels "context" .) | nindent 4 }}
  name: {{ include "base.fullname" . }}
spec:
  {{- with .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  selector:
    matchLabels: {{- include "base.selectorLabels" . | nindent 6 }}
  {{- with .Values.strategy }}
  updateStrategy: {{- toYaml . | nindent 4 }}
  {{- end }}
  template: {{- include "base.podTemplate" . | nindent 4 }}
{{- end }}
