{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with include "base.annotations" (dict "annotations" .Values.serviceAccount.annotations "context" $) }}
  annotations: {{- . | nindent 4 }}
  {{- end }}
  {{- with include "base.labels" (dict "labels" .Values.serviceAccount.labels "context" .) }}
  labels: {{- . | nindent 4 }}
  {{- end }}
  name: {{ include "base.serviceAccountName" . }}
{{- if ne .Values.serviceAccount.automount nil }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
{{- end }}
