{{- if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  {{- with include "base.annotations" (dict "annotations" .Values.configMap.annotations "context" $) }}
  annotations: {{- . | nindent 4 }}
  {{- end }}
  labels: {{- include "base.labels" (dict "labels" .Values.configMap.labels "context" .) | nindent 4 }}
  name: {{ include "base.fullname" . }}
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{- $rendered := include "base.render.value" (dict "value" $value "context" $) }}
  {{- if or (kindIs "map" $value) (kindIs "slice" $value) (contains "\n" $rendered) }}
  {{ $key }}: |
    {{- $rendered | nindent 4 }}
  {{- else }}
  {{ $key }}: {{ $rendered | quote }}
  {{- end }}
  {{- end }}
{{- end }}
