{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  {{- with include "base.annotations" (dict "annotations" .Values.secret.annotations "context" $) }}
  annotations: {{- . | nindent 4 }}
  {{- end }}
  labels: {{- include "base.labels" (dict "labels" .Values.secret.labels "context" .) | nindent 4 }}
  name: {{ include "base.fullname" . }}
type: {{ .Values.secret.type }}
{{- with .Values.secret.stringData }}
stringData:
  {{- range $key, $value := . }}
  {{ $key }}: {{ include "base.render.value" (dict "value" $value "context" $) | quote }}
  {{- end }}
{{- end }}
{{- with .Values.secret.data }}
data:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
