{{- if eq .Values.workload "statefulset" -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  {{- with include "base.annotations" (dict "annotations" .Values.annotations "context" .) }}
  annotations: {{- . | nindent 4 }}
  {{- end }}
  labels: {{- include "base.labels" (dict "labels" .Values.labels "context" .) | nindent 4 }}
  name: {{ include "base.fullname" . }}
spec:
  {{- if and (not .Values.autoscaling.enabled) (or .Values.replicas (eq .Values.replicas 0)) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- with .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  selector:
    matchLabels: {{- include "base.selectorLabels" . | nindent 6 }}
  serviceName: {{ default (include "base.fullname" .) .Values.serviceName }}
  {{- with .Values.podManagementPolicy }}
  podManagementPolicy: {{ . }}
  {{- end }}
  {{- with .Values.strategy }}
  updateStrategy: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.persistentVolumeClaimRetentionPolicy }}
  persistentVolumeClaimRetentionPolicy: {{- toYaml . | nindent 4 }}
  {{- end }}
  template: {{- include "base.podTemplate" . | nindent 4 }}
  {{- with .Values.volumeClaimTemplates }}
  volumeClaimTemplates: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
