# Publish chart to the GitHub Container Registry (GHCR) on push to main
name: Publish

on:
  push:
    branches:
      - main
    paths:
      - templates/**
      - Chart.yaml
      - values.yaml
      - README.md

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package  helm charts
        run: helm dependency build && helm package .

      - name: Push chart to GHCR
        run: helm push base-*.tgz oci://ghcr.io/${{ github.repository_owner }}/helm-charts
