# Publish chart to the GitHub Container Registry (GHCR) on push to main
name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - charts/base/**

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Login to GHCR
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get chart version
        run: echo "CHART_VERSION=$(helm show chart charts/base | yq .version)" | tee -a $GITHUB_ENV

      - name: Package helm chart
        run: helm package --dependency-update charts/base

      - name: Push chart to GHCR
        run: helm push base-${CHART_VERSION}.tgz oci://ghcr.io/${{ github.repository_owner }}/helm-charts

      - name: Create GitHub Release
        run: gh release create "${CHART_VERSION}" --title "${CHART_VERSION}" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
